services:
  postgres:
    image: postgres:16
    container_name: flood_pg
    environment:
      POSTGRES_USER: flood_user
      POSTGRES_PASSWORD: flood_pass
      POSTGRES_DB: flood_db
    ports:
      - "5432:5432"
    volumes:
      - flood_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: flood_redis
    ports:
      - "6379:6379"
    volumes:
      - flood_redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]



volumes:
  flood_pg_data:
  flood_redis_data: